import { Injectable } from '@angular/core';
import { range } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ComplaintsService {

  constructor() { }


data = [
  {
    referenceNumber: 'FIELD/2024/09/3',
    subject: 'Global fleet of connected vehicles',
    problemSubject: 'hazard service aimed at improving road safety through real-time alerts. Already rolled out in millions of vehicles across Europe',
    capa: '↪',
    country: 'Andorra',
    model: '890GD254',
    department: 'RND',
    criticality: 'Medium Critical',
    distributor: 'Mahindra',
    City: 'Hyderabad',
    serialno: '3001',
    status: 'Pending',
    Lead: 'Ayush',
    Feedback: 'test',
    TargetDate: '10-09-2025',
    FailureDate: '12-09-2025',
    ExpectedFinishDate: '12-09-2025',
    ActualFinishDate: '10-09-2025',
    steps: "15/15",
    responsibility: 'Ayush',
    complaintDate: '01-09-2025',
    customer: 'Global Motors',
    dueDate: '20-09-2025',
    complitionDate: '18-09-2025',
    range: Math.round(15/15*100),
  },
  {
    referenceNumber: 'FIELD/2024/09/6',
    subject: 'High-Performance Nissan Ariya NISMO',
    problemSubject: 'Nissan has unveiled the Ariya NISMO, a high-performance electric crossover designed for those who crave speed',
    capa: '↪',
    country: 'Angola',
    model: '7965735',
    department: 'RND',
    criticality: 'Medium Critical',
    distributor: 'Nissan',
    City: 'Mumbai',
    serialno: '3002',
    status: 'Pending',
    steps: "9/15",
    range: Math.round(9/15*100),
    Lead: 'Unassigned',
    Feedback: 'No feedback',
    TargetDate: '01-01-2026',
    FailureDate: '05-09-2025',
    ExpectedFinishDate: '01-01-2026',
    ActualFinishDate: '01-01-2026',
    responsibility: 'Roshan',
    complaintDate: '02-09-2025',
    customer: 'Zenith Auto',
    dueDate: '21-09-2025',
    complitionDate: '06-09-2025',
  },
  {
    referenceNumber: 'FIELD/2024/09/13',
    subject: 'Engine Overheating',
    problemSubject: 'I’ve noticed that my car’s engine is frequently overheating, especially during longer trips.',
    capa: '↪',
    country: 'Algeria',
    model: '5629375',
    department: 'RND',
    criticality: 'Medium Critical',
    distributor: 'Toyota',
    City: 'Delhi',
    serialno: '3003',
    status: 'Pending',
    steps: "4/15",
    range: Math.round(4/15*100),
    Lead: 'Unassigned',
    Feedback: 'No feedback',
    TargetDate: '01-01-2026',
    FailureDate: '07-09-2025',
    ExpectedFinishDate: '01-01-2026',
    ActualFinishDate: '01-01-2026',
    responsibility: 'Tejaswi',
    complaintDate: '03-09-2025',
    customer: 'Prime Vehicles',
    dueDate: '22-09-2025',
    complitionDate: '08-09-2025',
  },
  {
    referenceNumber: 'FIELD/2024/09/14',
    subject: 'Update Application Dependencies',
    problemSubject: 'If the issue comes from a dependency (NuGet, external library), make sure all your dependencies are up to date',
    capa: '↪',
    country: 'Algeria',
    model: '822NPV345',
    department: 'QA',
    criticality: 'Low Critical',
    distributor: 'Honda',
    City: 'Chennai',
    serialno: '3004',
    status: 'Closed',
    steps: "9/15",
    range: Math.round(9/15*100),
    Lead: 'Unassigned',
    Feedback: 'No feedback',
    TargetDate: '01-01-2026',
    FailureDate: '09-09-2025',
    ExpectedFinishDate: '01-01-2026',
    ActualFinishDate: '01-01-2026',
    responsibility: 'Navin',
    complaintDate: '04-09-2025',
    customer: 'NextGen Cars',
    dueDate: '23-09-2025',
    complitionDate: '10-09-2025',
  },
  {
    referenceNumber: 'FIELD/2024/09/15',
    subject: 'Verify DLL Versions',
    problemSubject: 'If you’re referencing external DLLs, ensure the correct versions of the DLLs are being used in both your development environment and your deployment environment.',
    capa: '↪',
    country: 'Algeria',
    model: '0428NPV345',
    department: 'RND',
    criticality: 'Medium Critical',
    distributor: 'Ford',
    City: 'Pune',
    serialno: '3005',
    status: 'Process',
    steps: "7/15",
    range: Math.round(7/15*100),
    Lead: 'Unassigned',
    Feedback: 'No feedback',
    TargetDate: '01-01-2026',
    FailureDate: '11-09-2025',
    ExpectedFinishDate: '01-01-2026',
    ActualFinishDate: '01-01-2026',
    responsibility: 'Ridhima',
    complaintDate: '05-09-2025',
    customer: 'AutoWorld',
    dueDate: '24-09-2025',
    complitionDate: '12-09-2025',
  },
  {
    referenceNumber: 'FIELD/2024/09/16',
    subject: 'Bumper Issue',
    problemSubject: 'Bumper Issue: Describe the specific problem with the bumper.',
    capa: '↪',
    country: 'Andorra',
    model: '544NPV345',
    department: 'RND',
    criticality: 'Low Critical',
    distributor: 'Hyundai',
    City: 'Bangalore',
    serialno: '3006',
    status: 'Hold',
    steps: "11/15",
    range: Math.round(11/15*100),
    Lead: 'Unassigned',
    Feedback: 'No feedback',
    TargetDate: '01-01-2026',
    FailureDate: '13-09-2025',
    ExpectedFinishDate: '01-01-2026',
    ActualFinishDate: '01-01-2026',
    responsibility: 'Surya',
    complaintDate: '06-09-2025',
    customer: 'DriveTech',
    dueDate: '25-09-2025',
    complitionDate: '14-09-2025',
  },
  {
    referenceNumber: 'FIELD/2024/09/23',
    subject: 'Error Testing',
    problemSubject: 'Bug free s/w application',
    capa: '↪',
    country: 'Andorra',
    model: '898NPV345',
    department: 'Test',
    criticality: 'Upper Level Critical',
    distributor: 'Mahindra',
    City: 'Kolkata',
    serialno: '3007',
    status: 'Pending',
    steps: "15/15",
    range: Math.round(15/15*100),
    Lead: 'Unassigned',
    Feedback: 'No feedback',
    TargetDate: '01-01-2026',
    FailureDate: '15-09-2025',
    ExpectedFinishDate: '01-01-2026',
    ActualFinishDate: '01-01-2026',
    responsibility: 'Ayush',
    complaintDate: '07-09-2025',
    customer: 'Global Motors',
    dueDate: '26-09-2025',
    complitionDate: '16-09-2025',
  },
  {
    referenceNumber: 'FIELD/2024/09/23',
    subject: 'Error Testing',
    problemSubject: 'Bug free s/w application',
    capa: '↪',
    country: 'Andorra',
    model: '348NEV345',
    department: 'Test',
    criticality: 'Upper Level Critical',
    distributor: 'Nissan',
    City: 'Ahmedabad',
    serialno: '3008',
    status: 'pending',
    steps: "10/15",
    range: Math.round(10/15*100),
    Lead: 'Unassigned',
    Feedback: 'No feedback',
    TargetDate: '01-01-2026',
    FailureDate: '17-09-2025',
    ExpectedFinishDate: '01-01-2026',
    ActualFinishDate: '01-01-2026',
    responsibility: 'Roshan',
    complaintDate: '08-09-2025',
    customer: 'Zenith Auto',
    dueDate: '27-09-2025',
    complitionDate: '16-09-2025',
  },
]
  getComplaints() {
    const departments = ['HD', 'Test', 'Manufacture', 'HR Department', 'IT Department', 'Painting Department', 'Component-Shop', 'Assembly line', 'Paint Shop', 'Body Shop'];
    return this.data.map(item => ({
      ...item,
      department: departments[Math.floor(Math.random() * departments.length)]
    }));
  }

}
